### ISSUE TITLE
Update concurrent ruby version

### ISSUE THREAD

**Issue by taq** [nathanstitt/guard-jest#2]
Thanks for this gem.

I was trying to install it with a recent app (Rails 6, Ruby 2.7.2) but I couldn't because of the `concurrent-ruby` version. It is asking for

```
    spec.add_dependency 'concurrent-ruby', '~> 1.0.4'
```
but with the other more recent dependencies it couldn't be installed. I cloned this repo, changed it to

```
    spec.add_dependency 'concurrent-ruby', '> 1.0.4'
```

on `Gemfile` and build and installed it locally, and it worked with no issues.

Could you please update the `concurrent-ruby` version?

Thanks!

**Comment by nathanstitt** [comment]
Hi @taq thanks for the heads up about the outdated version.  I've just published `0.2.0` which has it updated to the latest. 

Hope the gem works well for you!

**Comment by taq** [comment]
Thanks! ☺️

**Comment by taq** [comment]
Now we just need a new gem version! ;-)
